### ISSUE TITLE
Cmd DB 上に Cmd_ いらなくない？

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/tlm-cmd-db#19]
## 概要
Cmd DB 上に Cmd_ いらなくない？

## 詳細
Cmd_ ついてるのは，コード規約から．Cのコード上の都合
code generator でつければいい

## close条件
考えら

**Comment by meltingrabbit** [comment]
@chutaro どう思う？ WINGS でも Cmd_ あるの意味ないよね？

**Comment by chutaro** [comment]
個人的には消さなくていいかなと思います。コマンドであることが明示的でわかりやすいですし。

wingsでも、opsやコマンドログでは `RT.Cmd_hoge`のように表示してほしいですし、その前の段階でわざわざ cmd を消して DB に保存しておかなくてもいい気がします

**Comment by TomokiMochizuki** [comment]
個人的に，伊藤君の意見に同意ですね．
RT / TL がある時点でコマンドであることは明らかではある気がしますが，わざわざ消さなくてもいい気はしてます．
WINGS的には特に改修する項目がないので，改修するとしても，そこまで面倒なわけではないですが
Duplicate of #

**Comment by meltingrabbit** [comment]
なるほどなるほど．

今って， MOBC_RT.XXXX のところに，コマンド以外がくることってあったっけ？

課題意識としては，

- Cmd_ で始まることが必須，であれば，それは DB に書くべきではない
  - もし，下流で Cmd_ を識別するマイクロサービスなどが存在したとき，Cmd_ じゃないものが混在するとバグになったりするので
  - 必須なのであれば，必要なところでつければ良い（ex. code generator や WINGS 側)

ってのが大きかったけど，`わざわざ消さなくてもいい` という気持ちも理解．

**Comment by meltingrabbit** [comment]
今，WINGS ops で，衛星向け Cmd 以外のコマンド（地上局操作とか）ってどんな感じにしてますっけ？

同様に Cmd_HOGE ？

**Comment by chutaro** [comment]
> Cmd_ で始まることが必須，であれば，それは DB に書くべきではない

これは納得です。今は慣れてしまっているので Cmd_ から始まる CMD_DB の景色を見やすいなと思ってしまうのですが、まあ消しても大丈夫です

**Comment by chutaro** [comment]
tlm cmd generator と gs software で `Cmd` を付加して表示するなら消す方針で問題ないです。

**Comment by meltingrabbit** [comment]
影響範囲大きそうなので，来週の c2a core mtg でまた話しましょうか．gs sw の影響範囲わかってないので
